apiVersion: v1
kind: Service
metadata:
  name: {{ include "mesin10.fullname" . }}
  labels:
    {{- include "mesin10.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.portudp }}
      targetPort: {{ .Values.service.portudp }}
      nodePort: {{ .Values.service.portudp }}
      protocol: UDP
      name: customudp
  selector:
    {{- include "mesin10.selectorLabels" . | nindent 4 }}
